#target dependencies
#	rule to build
#

all: prog

prog: caveEntrance.o caveOfEternalDestiny.o caveOfShadows.o caveOfTheElders.o cavernOfTime.o echoOfDarkness.o eyeOfTheStalker.o fangOfTheWild.o FeatherOfTheGreatEagle.o forlornCavern.o glowingShard.o HourGlassOfEternity.o keyOfAThousandEchoes.o main.o messengerOfFate.o potionOfEnlightenment.o prismOfInnerCalm.o prismOfRecurrence.o relicOfTime.o shadowsEmbrace.o skeletonKey.o theForgottenPools.o totemOfHealingRain.o User.o world.o 
	g++ cave.hpp item.hpp caveEntrance.o caveOfEternalDestiny.o caveOfShadows.o caveOfTheElders.o cavernOfTime.o echoOfDarkness.o eyeOfTheStalker.o fangOfTheWild.o FeatherOfTheGreatEagle.o forlornCavern.o glowingShard.o HourGlassOfEternity.o keyOfAThousandEchoes.o messengerOfFate.o potionOfEnlightenment.o prismOfInnerCalm.o prismOfRecurrence.o relicOfTime.o shadowsEmbrace.o skeletonKey.o theForgottenPools.o totemOfHealingRain.o User.o world.o main.o -o prog

caveEntrance.o: caveEntrance.cpp
	g++ -c caveEntrance.cpp

caveOfEternalDestiny.o: caveOfEternalDestiny.cpp
	g++ -c caveOfEternalDestiny.cpp

caveOfShadows.o: caveOfShadows.cpp
	g++ -c caveOfShadows.cpp

caveOfTheElders.o: caveOfTheElders.cpp
	g++ -c caveOfTheElders.cpp

cavernOfTime.o: cavernOfTime.cpp
	g++ -c cavernOfTime.cpp

echoOfDarkness.o: echoOfDarkness.cpp
	g++ -c echoOfDarkness.cpp

eyeOfTheStalker.o: eyeOfTheStalker.cpp
	g++ -c eyeOfTheStalker.cpp

fangOfTheWild.o: fangOfTheWild.cpp
	g++ -c fangOfTheWild.cpp

FeatherOfTheGreatEagle.o: FeatherOfTheGreatEagle.cpp
	g++ -c FeatherOfTheGreatEagle.cpp

forlornCavern.o: forlornCavern.cpp
	g++ -c forlornCavern.cpp 

glowingShard.o: glowingShard.cpp
	g++ -c glowingShard.cpp

HourGlassOfEternity.o: HourGlassOfEternity.cpp
	g++ -c HourGlassOfEternity.cpp

keyOfAThousandEchoes.o: keyOfAThousandEchoes.cpp
	g++ -c keyOfAThousandEchoes.cpp

main.o: main.cpp
	g++ -c main.cpp

messengerOfFate.o: messengerOfFate.cpp
	g++ -c messengerOfFate.cpp

potionOfEnlightenment.o: potionOfEnlightenment.cpp
	g++ -c potionOfEnlightenment.cpp

prismOfInnerCalm.o: prismOfInnerCalm.cpp
	g++ -c prismOfInnerCalm.cpp

prismOfRecurrence.o: prismOfRecurrence.cpp
	g++ -c prismOfRecurrence.cpp

relicOfTime.o: relicOfTime.cpp
	g++ -c relicOfTime.cpp

shadowsEmbrace.o: shadowsEmbrace.cpp
	g++ -c shadowsEmbrace.cpp

skeletonKey.o: skeletonKey.cpp
	g++ -c skeletonKey.cpp

theForgottenPools.o: theForgottenPools.cpp
	g++ -c theForgottenPools.cpp

totemOfHealingRain.o: totemOfHealingRain.cpp
	g++ -c totemOfHealingRain.cpp

User.o: User.cpp
	g++ -c User.cpp

world.o: world.cpp
	g++ -c world.cpp

clean:
	rm *.o prog
